name: OpenTofu CI/CD with AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tofu:
    name: Deploy to AWS with OpenTofu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize OpenTofu
        run: tofu init

      - name: Format Check
        run: tofu fmt -check

      - name: Validate Configuration
        run: tofu validate

      - name: Plan Infrastructure
        run: tofu plan

      - name: Apply Infrastructure (Only on push to main)
        if: github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve
